name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment to deploy to'
        options:
          - prod
          - staging
          - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Doing something in '${{ github.event.inputs.environment }}' environment
        env:
          SECRET: ${{ secrets.ENV_SECRET }}
          VARIABLE: ${{ vars.ENV_NAME }}
        run:
          echo "Environment is $VARIABLE"