name: Deploy to Azure
on:
  #push:
  #  branches:
  #    main
  workflow_dispatch:
permissions:
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Placeholder for building app
        run: echo "Placeholder for building app..."
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to Azure
        run: |
          echo "Placeholder for doing something real..."
          az account list


