name: Integration Tests Azure
on:
  pull_request:
    branches:
      main
permissions:
  id-token: write
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Placeholder for building app
        run: echo "Placeholder for building app..."
      - name: 'Az CLI login'
        uses: azure/login@a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Do some integration tests or something in Azure
        run: |
          echo "Placeholder for doing something real..."
          az account list


