name: Integration Tests Azure
on:
  #pull_request:
  #  branches:
  #    main
  deployment_status
permissions:
  id-token: write
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder for building app
        run: echo "Placeholder for building app..."
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Do some integration tests or something in Azure
        run: |
          echo "Placeholder for doing something malicious..."
          az security setting list


